"""Test that with no fields selected for a stream automatic fields are still
replicated."""
from base import MSDynamics365CRMBaseTest
from tap_tester.base_suite_tests.automatic_fields_test import MinimumSelectionTest


class MSDynamics365CRMAutomaticFields(MinimumSelectionTest, MSDynamics365CRMBaseTest):
    """Test that with no fields selected for a stream automatic fields are
    still replicated."""

    @staticmethod
    def name():
        return "tap_tester_ms_dynamics_365_crm_automatic_fields_test"

    def streams_to_test(self):
        streams_to_exclude = set({
            'bookableresource',
            'bookableresourcebooking',
            'bookableresourcebookingheader',
            'bookableresourcecategory',
            'bookableresourcecategoryassn',
            'bookableresourcecharacteristic',
            'bookableresourcegroup',
            'competitor',
            'contract',
            'contractdetail',
            'entitlement',
            'entitlementchannel',
            'entitlementcontacts',
            'entitlementproducts',
            'entitlementtemplate',
            'entitlementtemplatechannel',
            'entitlementtemplateproducts',
            'equipment',
            'feedback',
            'incidentknowledgebaserecord',
            'incidentresolution',
            'invoice',
            'invoicedetail',
            'knowledgearticleincident',
            'knowledgearticleviews',
            'knowledgebaserecord',
            'msdyn_agreement',
            'msdyn_agreementbookingdate',
            'msdyn_agreementbookingincident',
            'msdyn_agreementbookingproduct',
            'msdyn_agreementbookingservice',
            'msdyn_bookableresourceassociation',
            'msdyn_bookingalert',
            'msdyn_bookingalertstatus',
            'msdyn_bookingjournal',
            'msdyn_bookingrule',
            'msdyn_bookingtimestamp',
            'msdyn_entitlementapplication',
            'msdyn_flwconfiguration',
            'msdyn_geofence',
            'msdyn_geofenceevent',
            'msdyn_geolocationtracking',
            'msdyn_incidenttype',
            'msdyn_incidenttypecharacteristic',
            'msdyn_incidenttypeproduct',
            'msdyn_incidenttyperesolution',
            'msdyn_incidenttypeservice',
            'msdyn_incidenttypeservicetask',
            'msdyn_incidenttypessetup',
            'msdyn_inspection',
            'msdyn_inspectionattachment',
            'msdyn_inspectiondefinition',
            'msdyn_inspectioninstance',
            'msdyn_inspectionresponse',
            'msdyn_inventoryadjustment',
            'msdyn_inventoryadjustmentproduct',
            'msdyn_inventoryjournal',
            'msdyn_inventorytransfer',
            'msdyn_nottoexceed',
            'msdyn_optimizationrequest',
            'msdyn_organizationalunit',
            'msdyn_postalcode',
            'msdyn_productinventory',
            'msdyn_purchaseorder',
            'msdyn_purchaseorderbill',
            'msdyn_purchaseorderproduct',
            'msdyn_purchaseorderreceipt',
            'msdyn_purchaseorderreceiptproduct',
            'msdyn_purchaseordersubstatus',
            'msdyn_requirementchange',
            'msdyn_requirementcharacteristic',
            'msdyn_requirementdependency',
            'msdyn_requirementgroup',
            'msdyn_requirementresourcecategory',
            'msdyn_requirementresourcepreference',
            'msdyn_resolution',
            'msdyn_resourcepaytype',
            'msdyn_resourcerequirement',
            'msdyn_resourcerequirementdetail',
            'msdyn_resourceterritory',
            'msdyn_rma',
            'msdyn_rmaproduct',
            'msdyn_rmareceipt',
            'msdyn_rmareceiptproduct',
            'msdyn_rmasubstatus',
            'msdyn_rtv',
            'msdyn_rtvproduct',
            'msdyn_rtvsubstatus',
            'msdyn_servicetasktype',
            'msdyn_shipvia',
            'msdyn_slakpi',
            'msdyn_systemuserschedulersetting',
            'msdyn_taxcode',
            'msdyn_taxcodedetail',
            'msdyn_timeentry',
            'msdyn_timegroupdetail',
            'msdyn_timeoffrequest',
            'msdyn_trade',
            'msdyn_tradecoverage',
            'msdyn_workhourtemplate',
            'msdyn_workorder',
            'msdyn_workorderincident',
            'msdyn_workordernte',
            'msdyn_workorderproduct',
            'msdyn_workorderresolution',
            'msdyn_workorderservice',
            'msdyn_workorderservicetask',
            'msdyn_workordersubstatus',
            'msdyn_workordertype',
            'opportunityproduct',
            'productpricelevel',
            'queueitem',
            'quote',
            'quotedetail',
            'salesliterature',
            'salesliteratureitem',
            'salesorder',
            'salesorderdetail',
            'serviceappointment',
            'sla',
            'slaitem',
            'slakpiinstance',
        })
        return self.expected_stream_names().difference(streams_to_exclude)
